{
    'name': 'Hospital Management',
    'version': '1.0.0',
    'category': 'Hospital',
    'author': 'Emre Sevindik',
    'summary': 'Hospital management system',
    'description': 'Hospital management system',
    'depends': ['mail', 'product'],
    'data': [
        'security/ir.model.access.csv',
        'data/patient_tag_data.xml',
        'data/patient.tag.csv',
        'data/sequence_data.xml',
        'wizard/cancel_appointment_view.xml',
        'views/menu.xml',
        'views/patient_view.xml',
        'views/male_patient_view.xml',
        'views/female_patient_view.xml',
        'views/pharmacy_view.xml',
        'views/appointment_view.xml',
        'views/patient_tag_view.xml',
        'views/operation_view.xml',

    ],
    'demo': [],
    'auto_install': False,
    'installable': True,
    'application': True,
    'sequence': -100,
    'license': 'LGPL-3',
}
